- hosts: "localhost"
  become: true

  tasks:
    - name: installing packages
      package: 
        name: ["ftp","vsftpd"]
        state: "installed"

    - name: Adding the users
      user:
        name: "mel"
        comment: John Doe
        password: "$1$JpQ2xfLx$Y8ORT7I4FYBpqKYTIseEY0"
    
    - name: Editing vsftpd.conf
      lineinfile:
        path: /etc/vsftpd.conf
        regexp: ".*chroot_local_user.*"
        line: chroot_local_user=YES
    
    - name: Editing pam.d/vsftpd
      lineinfile:
        path: /etc/pam.d/vsftpd
        regexp: ".*pam_shell.*"
        line: '# auth required  pam_shells.so'

    - name: starting the service
      service:
        name: "vsftpd"
        state: "started"

